# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./app
    steps:
      - name: Setup and run test Node
        uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - name: npm installation
        run: npm install
      - name: compose up
      - uses: isbang/compose-action@v1.2.0
        with:
          compose-file: "../docker-compose.yml"
      - name: Run test
        run: npm test
