# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
env:
  COUCHDB_USER: ${{ secrets.COUCHDB_USER }}
  COUCHDB_PASSWORD: ${{ secrets.COUCHDB_PASSWORD }}
  SESS_NAME: ${{ secrets.SESS_NAME }}
  SESSION_SECRET: ${{ secrets.SESSION_SECRET }}
  GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
  GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
  AMQP_URL: ${{ secrets.AMQP_URL }}
  APP_EMAIL: ${{ secrets.APP_EMAIL }}
  APP_EMAIL_PASS: ${{ secrets.APP_EMAIL_PASS }}
  
jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./app
    steps:
      - name: Setup and run test Node
        uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - name: npm installation
        run: npm install
      - name: docker compose up
        run: cd .. && docker-compose up -d 
      - name: docker-compose down
        run: cd .. && docker-compose down
